# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 995a0e76b40b44336c14801d446e1c0e8cca3d9f6f59328e32aba696cb638eb695ee07aa8826ef552aabec98daec0e5d80be0a6110c029eca4b78170060e9dfe

test:
  secret_key_base: 21661f3c3e91c575f9cba775a895613393a1cdc3885fb15fe1152c009da234fbff6fafec1214ba44880e961371e2d3c9a89f50b582d69c79aeb27e44e9fa3af1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
